apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: streamlit
          image: username/yourapp:latest
          ports:
            - containerPort: 8501
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: LoadBalancer  # Use NodePort or ClusterIP as per your needs
  ports:
    - port: 80
      targetPort: 8501
  selector:
    app: streamlit-app
